// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/product-service/repository/option-repository.go

// Package repository is a generated GoMock package.
package repository

import (
	dtos "chilindo/src/product-service/dtos"
	models "chilindo/src/product-service/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIOptionRepository is a mock of IOptionRepository interface.
type MockIOptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIOptionRepositoryMockRecorder
}

// MockIOptionRepositoryMockRecorder is the mock recorder for MockIOptionRepository.
type MockIOptionRepositoryMockRecorder struct {
	mock *MockIOptionRepository
}

// NewMockIOptionRepository creates a new mock instance.
func NewMockIOptionRepository(ctrl *gomock.Controller) *MockIOptionRepository {
	mock := &MockIOptionRepository{ctrl: ctrl}
	mock.recorder = &MockIOptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOptionRepository) EXPECT() *MockIOptionRepositoryMockRecorder {
	return m.recorder
}

// CreateOption mocks base method.
func (m *MockIOptionRepository) CreateOption(dto *dtos.CreateOption) (*models.Option, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOption", dto)
	ret0, _ := ret[0].(*models.Option)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOption indicates an expected call of CreateOption.
func (mr *MockIOptionRepositoryMockRecorder) CreateOption(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOption", reflect.TypeOf((*MockIOptionRepository)(nil).CreateOption), dto)
}

// DeleteOption mocks base method.
func (m *MockIOptionRepository) DeleteOption(dto *dtos.OptionById) (*models.Option, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOption", dto)
	ret0, _ := ret[0].(*models.Option)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOption indicates an expected call of DeleteOption.
func (mr *MockIOptionRepositoryMockRecorder) DeleteOption(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOption", reflect.TypeOf((*MockIOptionRepository)(nil).DeleteOption), dto)
}

// GetOption mocks base method.
func (m *MockIOptionRepository) GetOption(dto *dtos.OptionById) (*[]models.Option, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOption", dto)
	ret0, _ := ret[0].(*[]models.Option)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOption indicates an expected call of GetOption.
func (mr *MockIOptionRepositoryMockRecorder) GetOption(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOption", reflect.TypeOf((*MockIOptionRepository)(nil).GetOption), dto)
}

// GetOptionById mocks base method.
func (m *MockIOptionRepository) GetOptionById(dto *dtos.OptionById) (*models.Option, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptionById", dto)
	ret0, _ := ret[0].(*models.Option)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptionById indicates an expected call of GetOptionById.
func (mr *MockIOptionRepositoryMockRecorder) GetOptionById(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptionById", reflect.TypeOf((*MockIOptionRepository)(nil).GetOptionById), dto)
}

// UpdateOption mocks base method.
func (m *MockIOptionRepository) UpdateOption(dto *dtos.UpdateOptionBy) (*models.Option, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOption", dto)
	ret0, _ := ret[0].(*models.Option)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOption indicates an expected call of UpdateOption.
func (mr *MockIOptionRepositoryMockRecorder) UpdateOption(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOption", reflect.TypeOf((*MockIOptionRepository)(nil).UpdateOption), dto)
}
